import { Product } from "@/types/ProductTypes";

export const dummyProducts: Product[] = [
    {
      productid: 1,
      title: "Product 1",
      category: "Shoes",
      maincategory: "fashion",
      price: "50.00",
      discount: "40.00",
      stars: 4,
      isnew: true,
      issale: true,
      isdiscount: true,
      colors: [{ colorid: 1, name: "Red", colorname: "red", colorclass: "bg-red-500" }],
      sizes: [{ sizeid: 1, name: "M", sizename: "Medium", instock: true }],
      reviewCount: 120,
      images: { imageid: 1, imglink: "/images/product1.jpg", imgalt: "Product 1" }
    },
    {
      productid: 2,
      title: "Product 2",
      category: "Bags",
      maincategory: "fashion",
      price: "100.00",
      discount: "85.00",
      stars: 5,
      isnew: false,
      issale: true,
      isdiscount: false,
      colors: [{ colorid: 2, name: "Blue", colorname: "blue", colorclass: "bg-blue-500" }],
      sizes: [{ sizeid: 2, name: "L", sizename: "Large", instock: true }],
      reviewCount: 80,
      images: { imageid: 2, imglink: "/images/product2.jpg", imgalt: "Product 2" }
    },
    {
      productid: 3,
      title: "Product 3",
      category: "Watches",
      maincategory: "accessories",
      price: "150.00",
      discount: "130.00",
      stars: 3,
      isnew: true,
      issale: false,
      isdiscount: true,
      colors: [{ colorid: 3, name: "Black", colorname: "black", colorclass: "bg-black" }],
      sizes: [{ sizeid: 3, name: "S", sizename: "Small", instock: false }],
      reviewCount: 50,
      images: { imageid: 3, imglink: "/images/product3.jpg", imgalt: "Product 3" }
    },
    {
      productid: 4,
      title: "Product 4",
      category: "Hats",
      maincategory: "fashion",
      price: "25.00",
      discount: "20.00",
      stars: 2,
      isnew: false,
      issale: false,
      isdiscount: false,
      colors: [{ colorid: 4, name: "Green", colorname: "green", colorclass: "bg-green-500" }],
      sizes: [{ sizeid: 4, name: "XL", sizename: "Extra Large", instock: true }],
      reviewCount: 30,
      images: { imageid: 4, imglink: "/images/product4.jpg", imgalt: "Product 4" }
    },
    {
      productid: 5,
      title: "Product 5",
      category: "Shirts",
      maincategory: "fashion",
      price: "75.00",
      discount: "65.00",
      stars: 4,
      isnew: true,
      issale: true,
      isdiscount: true,
      colors: [{ colorid: 5, name: "Yellow", colorname: "yellow", colorclass: "bg-yellow-500" }],
      sizes: [{ sizeid: 5, name: "M", sizename: "Medium", instock: true }],
      reviewCount: 90,
      images: { imageid: 5, imglink: "/images/product5.jpg", imgalt: "Product 5" }
    }
  ];